language: c

os:
  - linux

compiler:
  - clang
  - gcc

python:
  - "2.7"

addons:
  apt:
    packages:
    - libgsl0-dev
    - gfortran

before_install:
  - mkdir build

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl; fi

before_script:
  - cd build
  - cmake  -DCMAKE_BUILD_TYPE=Release ../
  - cmake --build . -- -j2

script:
  - cd distributions/Python/pyamtrack && python generate_Py_wrapper.py
